### ISSUE TITLE
fail to run script

### ISSUE THREAD

**Issue by wzjscmr** [garganshul108/Code-With-Mosh-Playlist-Downloader#11]
I try to download the Node.js course by run
```
chmod 777 ./playlist_downloader.sh
playlist_downloader.sh https://codewithmosh.com/courses/293204/lectures/4509750
```

And here's the error message:

> ./playlist_downloader.sh https://codewithmosh.com/courses/293204/lectures/4509750
> scraping title page from https://codewithmosh.com/courses/293204/lectures/4509750
>   File "scrape_via_login.py", line 9
>     LOGIN_URL = "https://sso.teachable.com/secure/".SCHOOL_ID."/users/sign_in?clean_login=true&reset_purchase_session=1"
>                                                                                                                        ^
> SyntaxError: invalid syntax
> scraped into title.html
> local scraping of contents
> Traceback (most recent call last):
>   File "scrape_content_urls.py", line 1, in <module>
>     from bs4 import BeautifulSoup
> ImportError: No module named bs4
> contents scraped
> removing unneccesary title.html
> .txt
>   File "scrape_list_via_login.py", line 10
>     LOGIN_URL = "https://sso.teachable.com/secure/".SCHOOL_ID."/users/sign_in?clean_login=true&reset_purchase_session=1"

**Comment by garganshul108** [comment]
Try it now! I think the bug is fixed now.
- Report if the same error persists (reopen the issue)
- Report any new bug if you come across
Thanks :+1:

**Comment by wzjscmr** [comment]
Now I'm getting those errors on Win10 with python3 installed
> scraping title page from https://codewithmosh.com/courses/293204/lectures/4509750
> Traceback (most recent call last):
>   File "scrape_via_login.py", line 3, in <module>
>     from lxml import html
> ModuleNotFoundError: No module named 'lxml'
> scraped into title.html
> local scraping of contents
> Traceback (most recent call last):
>   File "scrape_content_urls.py", line 1, in <module>
>     from bs4 import BeautifulSoup
> ModuleNotFoundError: No module named 'bs4'
> contents scraped
> removing unneccesary title.html
> .txt
> Traceback (most recent call last):
>   File "scrape_list_via_login.py", line 3, in <module>
>     from lxml import html
> ModuleNotFoundError: No module named 'lxml'
> ./playlist_downloader.sh: line 18: $'\r': command not found
> ./playlist_downloader.sh: line 20: $'\r': command not found

I'm relatively new to python. I only have python3 installed on my Win10 PC, should I also install python2  and install all those missing module like lmxl, beautifulsoup ?

**Comment by garganshul108** [comment]
Okay I see, these are the python3 modules that aren't installed on your system.

I will include them in the prerequisites soon. :+1: 
Thanks again :smile:

**Comment by wzjscmr** [comment]
Okay, maybe I should wait for the GUI version because I don't quite know how to work with python.  Thanks for your contribution 😄.

**Comment by garganshul108** [comment]
Or you want to **view** the lectures of Nodejs, then you can try [this blog](https://freelectureslinks.blogspot.com/2019/09/node-js-playlist.html).
It has all the lectures which you will get after scraping the list.

And in case you want the **downloaded lectures** only then mail me sci.agarg@gmail.com

**Comment by wzjscmr** [comment]
I'll definitely do that, Thanks.

**Comment by wzjscmr** [comment]
I found myself an ubuntu machine and finally be able to download the course using 

`./curl_script.sh NodeJS.txt    `

But I still can't scrape the playlist by myself, I tried to scrape the python playlist by run

 `./playlist_downloader.sh https://codewithmosh.com/courses/423295/lectures/6781718
`

Then I only had the video title in my .txt without the video url,

> https://sso.teachable.com/secure/xxxxxx/users/sign_in?clean_login=true&reset_purchase_session=1
> 1.1-WhatisPython(3:21)
> 2.2-InstallingPython(2:20)
> 3.3-CodeEditors(0:58)
> 4.4-YourFirstPythonProgram(2:25)
> 5.5-PythonExtension(2:52)
> 6.6-LintingPythonCode(4:14)
> 7.7-FormattingPythonCode(3:54)
> 8.8-RunningPythonCode(2:59)
> 9.9-PythonImplementations(2:28)
> 10.10-HowPythonCodeisExecuted(2:46)
> ……
> END

And here's the log:

> scraping title page from https://codewithmosh.com/courses/423295/lectures/6781718
> scraped into title.html
> local scraping of contents
> contents scraped
> removing unneccesary title.html
> .txt
> Traceback (most recent call last):
>   File "scrape_list_via_login.py", line 54, in <module>
>     main()
>   File "scrape_list_via_login.py", line 42, in main
>     result = session_requests.get(URL, headers = dict(referer = URL))
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 546, in get
>     return self.request('GET', url, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 519, in request
>     prep = self.prepare_request(req)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 462, in prepare_request
>     hooks=merge_hooks(request.hooks, self.hooks),
>   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 313, in prepare
>     self.prepare_url(url, params)
>   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 387, in prepare_url
>     raise MissingSchema(error)
> requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

**Comment by garganshul108** [comment]
No, I think I need some serious help here! :(

Problem is I don't have a valid login-password to check the script (my subscription got expired in July)

**Comment by wzjscmr** [comment]
My fault, I thought I don't have to have a subscription to scrape the list. 
I can use the non-subscription account to scrape the URLs of those preview videos.
I'll try it again when I have the subscription.
I'll close the issue for now.

**Comment by garganshul108** [comment]
Huh! Finally, hoping that's the only problem here. :sweat_smile: 

:crossed_fingers:
