### ISSUE TITLE
I'm getting this error

### ISSUE THREAD

**Issue by ameykulkarni10** [garganshul108/Code-With-Mosh-Playlist-Downloader#20]
![Screenshot (168)](https://user-images.githubusercontent.com/39147555/68907380-90c6d180-076d-11ea-8b80-09d5266fc819.png)

**Comment by garganshul108** [comment]
Have you tried putting in all the relevant credentials at the right places?

**Comment by kxomk** [comment]
Hi anshul I got the same error. Csrf-token is not being fetched by the code for the current school-id. I tried the code to see if I could login to some other website and it was fetching token there.

**Comment by aahmed9to6** [comment]
The same issue happens to me. Any luck guys?

**Comment by ghulammurtaza** [comment]
same issue

**Comment by Weyla** [comment]
Same thing.

**Comment by bnimit** [comment]
Was anyone able to get it to work ?

**Comment by jamespavett** [comment]
@garganshul108 I am getting the same error as well, any updates?

**Comment by alaadahmed** [comment]
the same here also.

**Comment by RabihJabr29** [comment]
Hello @garganshul108  i am getting the error, any help guys??

**Comment by garganshul108** [comment]
This module is based on scraping dependent on site architecture, tokens and formats.
I think the format of the site has been changed by codewithmosh community hence the scraper isn't able to fetch the relevant token values.

**Comment by icaptnbob** [comment]
I'm still getting this same error. Has this been fixed?
