### ISSUE TITLE
I tried to follow the steps but no result , pls help 

### ISSUE THREAD

**Issue by mondimohamed** [garganshul108/Code-With-Mosh-Playlist-Downloader#27]
Hi , I tried to run Linux command from windows , it works but no result . Also playlist_downloaded.sh is not exist . 
please help 
Thanks in advance

**Comment by garganshul108** [comment]
Have you considered this possibility that 'running Linux command from windows can be a problem'?

**Comment by mondimohamed** [comment]
I'm not sure that is the problem , commands didn't give any error but also
no result came .
